version: '3'
services:
  mongodb:
    image: mongo
    container_name: delegation-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_PASSWORD: $TEZOS_DELEGATION_MONGO_INITDB_ROOT_PASSWORD
      MONGO_INITDB_ROOT_USERNAME: $TEZOS_DELEGATION_MONGO_INITDB_ROOT_USERNAME
      MONGO_INITDB_DATABASE: tezos_delegation