debug: true
environment: dev
api:
  tezos:
    debug: false
    timeout: 5s
    baseUrl: ""
datastore:
  mongo:
    uri: ""
    connectTimeout: 5s
    heartbeatInterval: 30s
    timeout: 2s
    username: ""
    password: ""